version: '3.8'

services:
  web:
    container_name: web_c
    hostname: web_addr
    image: ${FASTAPI_IMAGE}
    command: >
      bash -c "${FASTAPI_INIT_CMD}
      && ${FASTAPI_CMD}"
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./project:/usr/src/ # no need for production
    networks:
      - poke-net
    depends_on:
      - redis

  redis:
    container_name: redis_c
    hostname: redis_addr
    image: "redis:alpine"
    networks:
      - poke-net

networks:
  poke-net:
    name: poke-net